spin_version = "1"
name = "hello-spin"
version = "0.1.0"
authors = ["you@example.com"]
description = "Hello world from pure Cargo with Spin SDK!"

[[component]]
id = "hello"
source = "target/wasm32-wasi/release/hello_spin.wasm"
allowed_http_hosts = []
[component.trigger]
type = "http"
[component.trigger.http]
route = "/hello"
