name: Build and Push WASM to GHCR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}


permissions:
  packages: write
  statuses: write
  checks: write
  contents: write


jobs:
    build-container:
        name: 'Build & push image'
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout'
            uses: actions/checkout@v4

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v3
          - name: Log in to the Container registry
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ github.token }}
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ env.REGISTRY }}/${{ env.REPO }}
              tags: |
                type=ref,event=branch
                type=ref,event=pr
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              platforms: linux/amd64
              file: Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
